/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main.index'
import { Route as ChatContactIdRouteImport } from './routes/chat.$contactId'
import { Route as MainWordbookRouteImport } from './routes/_main.wordbook'
import { Route as MainVocabularyRouteImport } from './routes/_main.vocabulary'
import { Route as MainMeRouteImport } from './routes/_main.me'
import { Route as MainContactsRouteImport } from './routes/_main.contacts'
import { Route as MainAssessmentRouteImport } from './routes/_main.assessment'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const ChatContactIdRoute = ChatContactIdRouteImport.update({
  id: '/chat/$contactId',
  path: '/chat/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const MainWordbookRoute = MainWordbookRouteImport.update({
  id: '/wordbook',
  path: '/wordbook',
  getParentRoute: () => MainRoute,
} as any)
const MainVocabularyRoute = MainVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => MainRoute,
} as any)
const MainMeRoute = MainMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => MainRoute,
} as any)
const MainContactsRoute = MainContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => MainRoute,
} as any)
const MainAssessmentRoute = MainAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/assessment': typeof MainAssessmentRoute
  '/contacts': typeof MainContactsRoute
  '/me': typeof MainMeRoute
  '/vocabulary': typeof MainVocabularyRoute
  '/wordbook': typeof MainWordbookRoute
  '/chat/$contactId': typeof ChatContactIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/assessment': typeof MainAssessmentRoute
  '/contacts': typeof MainContactsRoute
  '/me': typeof MainMeRoute
  '/vocabulary': typeof MainVocabularyRoute
  '/wordbook': typeof MainWordbookRoute
  '/chat/$contactId': typeof ChatContactIdRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_main/assessment': typeof MainAssessmentRoute
  '/_main/contacts': typeof MainContactsRoute
  '/_main/me': typeof MainMeRoute
  '/_main/vocabulary': typeof MainVocabularyRoute
  '/_main/wordbook': typeof MainWordbookRoute
  '/chat/$contactId': typeof ChatContactIdRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/assessment'
    | '/contacts'
    | '/me'
    | '/vocabulary'
    | '/wordbook'
    | '/chat/$contactId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/assessment'
    | '/contacts'
    | '/me'
    | '/vocabulary'
    | '/wordbook'
    | '/chat/$contactId'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/login'
    | '/onboarding'
    | '/_main/assessment'
    | '/_main/contacts'
    | '/_main/me'
    | '/_main/vocabulary'
    | '/_main/wordbook'
    | '/chat/$contactId'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ChatContactIdRoute: typeof ChatContactIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/chat/$contactId': {
      id: '/chat/$contactId'
      path: '/chat/$contactId'
      fullPath: '/chat/$contactId'
      preLoaderRoute: typeof ChatContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/wordbook': {
      id: '/_main/wordbook'
      path: '/wordbook'
      fullPath: '/wordbook'
      preLoaderRoute: typeof MainWordbookRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/vocabulary': {
      id: '/_main/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof MainVocabularyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/me': {
      id: '/_main/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MainMeRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/contacts': {
      id: '/_main/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof MainContactsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/assessment': {
      id: '/_main/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof MainAssessmentRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainAssessmentRoute: typeof MainAssessmentRoute
  MainContactsRoute: typeof MainContactsRoute
  MainMeRoute: typeof MainMeRoute
  MainVocabularyRoute: typeof MainVocabularyRoute
  MainWordbookRoute: typeof MainWordbookRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAssessmentRoute: MainAssessmentRoute,
  MainContactsRoute: MainContactsRoute,
  MainMeRoute: MainMeRoute,
  MainVocabularyRoute: MainVocabularyRoute,
  MainWordbookRoute: MainWordbookRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ChatContactIdRoute: ChatContactIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
